name: Deploy Website

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Success Message
        run: echo "GitHub Actions Pipeline Is Working"
